import { basename } from 'node:path';
import { backtest } from './backtest.js';
import type { Config } from './config.js';
import type { Commit } from './git.js';
import { buildIndex } from './index.js';

const esc = (s: string): string => s.replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`);

/** A self-contained HTML report: no network access, no external assets. */
export function renderReport(
  root: string,
  history: readonly Commit[],
  tracked: ReadonlySet<string>,
  cfg: Config,
): string {
  const idx = buildIndex(history, cfg);
  const exists = (p: string): boolean => tracked.has(p);
  const pairs = idx.pairs(400).filter((p) => exists(p.a) && exists(p.b));
  const hubs = idx
    .hubs(60)
    .filter((h) => exists(h.file))
    .slice(0, 12);
  const bt = backtest(history, exists, cfg, { testCommits: 300, trialsPerCommit: 8, sweep: [] });
  const graphPairs = pairs.slice(0, 70);
  const nodeSet = new Set(graphPairs.flatMap((p) => [p.a, p.b]));
  const nodes = [...nodeSet].map((id) => ({ id, touches: idx.touches(id) }));
  const links = graphPairs.map((p) => ({ s: p.a, t: p.b, w: p.confidence, n: p.support }));
  const data = JSON.stringify({ nodes, links }).replace(/</g, '\\u003c');
  const pct = (x: number): string => `${Math.round(x * 100)}%`;
  const name = esc(basename(root));
  const row = (cells: string[]): string => `<tr>${cells.map((c) => `<td>${c}</td>`).join('')}</tr>`;
  const pairRows = pairs
    .slice(0, 25)
    .map((p) =>
      row([
        `<code>${esc(p.a)}</code>`,
        `<code>${esc(p.b)}</code>`,
        String(p.support),
        pct(p.confidence),
      ]),
    )
    .join('');
  const hubRows = hubs
    .map((h) => row([`<code>${esc(h.file)}</code>`, String(h.touches), String(h.partners)]))
    .join('');
  const btBlock =
    bt.trials > 0
      ? `<div class="stats">
  <div><b>${pct(bt.primary.recall)}</b><span>of forgotten files would be flagged</span></div>
  <div><b>${pct(bt.primary.precision)}</b><span>of flags hit the forgotten file</span></div>
  <div><b>${pct(bt.primary.nagRate)}</b><span>of complete commits would still warn</span></div>
</div>
<p class="muted">Replayed over the last ${bt.commits} multi-file commits (${bt.trials} held-out files), training only on earlier history, at ${pct(cfg.minConfidence)} confidence.</p>`
      : '<p class="muted">Not enough multi-file history to backtest.</p>';

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>cochange report: ${name}</title>
<style>
:root{--bg:#fff;--fg:#1a1d21;--mut:#5b6572;--line:#e3e6ea;--acc:#0b6bcb;--card:#f6f8fa}
@media(prefers-color-scheme:dark){:root{--bg:#0e1116;--fg:#e6e9ee;--mut:#8b95a3;--line:#262c35;--acc:#58a6ff;--card:#161b22}}
body{margin:0;background:var(--bg);color:var(--fg);font:15px/1.5 system-ui,sans-serif}
main{max-width:980px;margin:0 auto;padding:32px 20px 64px}
h1{font-size:24px;margin:0 0 4px}h2{font-size:17px;margin:36px 0 10px}
.muted{color:var(--mut)}code{font:13px ui-monospace,monospace}
table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:7px 10px;border-bottom:1px solid var(--line);word-break:break-all}
th{color:var(--mut);font-weight:600;font-size:13px}
.stats{display:flex;gap:12px;flex-wrap:wrap}.stats div{flex:1;min-width:180px;background:var(--card);border:1px solid var(--line);border-radius:8px;padding:14px}
.stats b{display:block;font-size:28px}.stats span{color:var(--mut);font-size:13px}
#graph{width:100%;height:520px;background:var(--card);border:1px solid var(--line);border-radius:8px}
#tip{min-height:22px;color:var(--mut);font-size:13px;margin-top:6px}
</style></head><body><main>
<h1>${name}</h1>
<p class="muted">${history.length.toLocaleString('en-US')} commits read · ${idx.commitCount.toLocaleString('en-US')} used · ${pairs.length} strong pairs · generated by cochange</p>
<h2>How trustworthy is the signal here?</h2>
${btBlock}
<h2>Coupling map</h2>
<svg id="graph" role="img" aria-label="Files that change together"></svg>
<div id="tip">Hover a file. Thicker lines mean the files change together more often. Drag to move.</div>
<h2>Strongest pairs</h2>
<table><tr><th>File</th><th>Usually changes with</th><th>Commits together</th><th>Confidence</th></tr>${pairRows}</table>
<h2>Files with the most hidden companions</h2>
<table><tr><th>File</th><th>Commits</th><th>Strong partners</th></tr>${hubRows}</table>
</main>
<script>
const data=${data};
const svg=document.getElementById('graph'),NS='http://www.w3.org/2000/svg',tip=document.getElementById('tip');
const W=980,H=520;svg.setAttribute('viewBox','0 0 '+W+' '+H);
const nodes=data.nodes.map((n,i)=>({...n,x:W/2+Math.cos(i)*200,y:H/2+Math.sin(i)*150,vx:0,vy:0}));
const byId=Object.fromEntries(nodes.map(n=>[n.id,n]));
const links=data.links.map(l=>({...l,a:byId[l.s],b:byId[l.t]}));
const el=(t,a)=>{const e=document.createElementNS(NS,t);for(const k in a)e.setAttribute(k,a[k]);return e};
const css=getComputedStyle(document.documentElement);
const lineEls=links.map(l=>{const e=el('line',{stroke:css.getPropertyValue('--acc'),'stroke-opacity':.25+.5*l.w,'stroke-width':1+3*l.w});svg.appendChild(e);return e});
const nodeEls=nodes.map(n=>{const g=el('g',{style:'cursor:grab'});g.appendChild(el('circle',{r:4+Math.min(10,Math.sqrt(n.touches)),fill:css.getPropertyValue('--acc')}));
 const t=el('text',{x:8,y:4,'font-size':10,fill:css.getPropertyValue('--fg')});t.textContent=n.id.split('/').pop();g.appendChild(t);svg.appendChild(g);
 g.addEventListener('mouseenter',()=>{const ls=links.filter(l=>l.a===n||l.b===n);tip.textContent=n.id+' · '+n.touches+' commits · '+ls.length+' coupled files shown'});
 let drag=false;g.addEventListener('pointerdown',e=>{drag=true;g.setPointerCapture(e.pointerId)});
 g.addEventListener('pointerup',()=>{drag=false;n.fixed=false});
 g.addEventListener('pointermove',e=>{if(!drag)return;const r=svg.getBoundingClientRect();n.x=(e.clientX-r.left)*W/r.width;n.y=(e.clientY-r.top)*H/r.height;n.fixed=true;n.vx=n.vy=0;tick.alpha=1});
 return g});
const tick=()=>{tick.alpha=Math.max(0,(tick.alpha??1)-0.004);
 for(const a of nodes)for(const b of nodes){if(a===b)continue;let dx=a.x-b.x,dy=a.y-b.y,d=dx*dx+dy*dy||1;if(d<60000){const f=900/d;a.vx+=dx*f;a.vy+=dy*f}}
 for(const l of links){const dx=l.b.x-l.a.x,dy=l.b.y-l.a.y,d=Math.sqrt(dx*dx+dy*dy)||1,f=(d-90)*0.02*l.w;l.a.vx+=dx/d*f;l.a.vy+=dy/d*f;l.b.vx-=dx/d*f;l.b.vy-=dy/d*f}
 for(const n of nodes){if(n.fixed)continue;n.vx+=(W/2-n.x)*0.004;n.vy+=(H/2-n.y)*0.006;n.x=Math.max(20,Math.min(W-90,n.x+n.vx*tick.alpha));n.y=Math.max(14,Math.min(H-14,n.y+n.vy*tick.alpha));n.vx*=.6;n.vy*=.6}
 links.forEach((l,i)=>{const e=lineEls[i];e.setAttribute('x1',l.a.x);e.setAttribute('y1',l.a.y);e.setAttribute('x2',l.b.x);e.setAttribute('y2',l.b.y)});
 nodes.forEach((n,i)=>nodeEls[i].setAttribute('transform','translate('+n.x+','+n.y+')'));
 if(tick.alpha>0)requestAnimationFrame(tick)};
tick.alpha=1;requestAnimationFrame(tick);
</script></body></html>
`;
}
